# Generated by Django 4.1.7 on 2023-03-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.TextField(default='Band description'),
        ),
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='band_images'),
        ),
    ]
