# Generated by Django 4.1.7 on 2023-03-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_band_description_band_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='id',
        ),
        migrations.AddField(
            model_name='band',
            name='band_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
