# Generated by Django 4.1.7 on 2023-03-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_remove_band_id_band_band_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='band_id',
        ),
        migrations.AddField(
            model_name='band',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
